name: CI

on:
  push:
    branches: [ master ]

jobs:
  
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    
    - name: Setup Node.js environment
      uses: actions/setup-node@v1.4.3
      with:
        node-version: 12.x
    
    # install depencendies yarn/npm
    - name: Install dependencies
      run: yarn
      
    # build app
    - name: Run Build
      run: yarn build
    
    - name: copy dist to Digital Ocean
      uses: appleboy/scp-action@master
      with:
        host: ${{ secrets.SSH_HOST }}
        username: ${{ secrets.SSH_USER }}
        key: ${{ secrets.SSH_KEY }}
        port: ${{ secrets.SSH_PORT }}
        source: "."
        target: "~/app/gobarber-backend"

