name: CI

on:
  push:
    branches: [ master ]

jobs:
  
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    
    - name: Setup Node.js environment
      uses: actions/setup-node@v1.4.3
      with:
        node-version: 12.x
    
    # install depencendies yarn/npm
    - name: Install dependencies
      run: yarn
      
    # Running tests
    - name: Run tests
      run: yarn test
      
    # build app
    - name: Run Build
      run: yarn build
    
    - name: Copy dist to Digital Ocean
      uses: appleboy/scp-action@master
      with:
        host: ${{ secrets.SSH_HOST }}
        username: ${{ secrets.SSH_USER }}
        key: ${{ secrets.SSH_KEY }}
        port: ${{ secrets.SSH_PORT }}
        source: ".,!node_modules"
        target: "~/app/gobarber-backend"
    
    - name: Run Production Scripts on Digital Ocean
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.SSH_HOST }}
        username: ${{ secrets.SSH_USER }}
        key: ${{ secrets.SSH_KEY }}
        port: ${{ secrets.SSH_PORT }}
        script: |
          cd ~/app/node-deploy
          yarn
          ./node_modules/.bin/typeorm migration:run
          pm2 restart gobarber-backend

